### ISSUE TITLE
after sleep, shutdown on mac os restart pc ?

### ISSUE THREAD

**Issue by souhaiebtar** [Crap-Mayur/Lenovo-Thinkpad-L480-Hackintosh-Opencore#3]
hey, do you have the problem that after going to sleep, when i try to shutdown the pc under macos , it restart the pc ?

i already tried  it but it doesn't work

https://dortania.github.io/OpenCore-Post-Install/usb/misc/shutdown.html

https://github.com/Koala166/The-TLDR-Guide-of-Fixing-Shutdown-Restart

**Comment by Crap-Mayur** [comment]
Bro u will need to patch ur usb and try to check ur trackpad once that it is i2cElan or different and in bios turn off boot from network and all 

Plz give star to my repo ❤️

**Comment by souhaiebtar** [comment]
it s elan, and about usb is not already included in your efi folder ?

**Comment by Crap-Mayur** [comment]
Well why not try patching it again

**Comment by souhaiebtar** [comment]
okay, but does it happen for you or not ?

**Comment by Crap-Mayur** [comment]
No mine works fine

**Comment by souhaiebtar** [comment]
@Crap-Mayur sorry if i'm  disturbing you, but do you think that it's the main reason ? and if yes , do you know a good tutorial for usb mapping because there is a lot on the internet ? or how you did it in your case ? sorry again
and thanks anyway
